// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.3
// source: yandex/cloud/priv/quota/quota.proto

package quota

import (
	_ "github.com/doublecloud/tross/cloud/bitbucket/private-api/yandex/cloud/priv"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Quota struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CloudId string         `protobuf:"bytes,1,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	Metrics []*QuotaMetric `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *Quota) Reset() {
	*x = Quota{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quota) ProtoMessage() {}

func (x *Quota) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quota.ProtoReflect.Descriptor instead.
func (*Quota) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{0}
}

func (x *Quota) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

func (x *Quota) GetMetrics() []*QuotaMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type QuotaMetric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // formatted as <domain>.<metric>.<unit>, e.g. mdb.hdd.size
	// Deprecated: Marked as deprecated in yandex/cloud/priv/quota/quota.proto.
	Value int64   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // use 'usage' field instead
	Limit int64   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Usage float64 `protobuf:"fixed64,4,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *QuotaMetric) Reset() {
	*x = QuotaMetric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuotaMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaMetric) ProtoMessage() {}

func (x *QuotaMetric) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaMetric.ProtoReflect.Descriptor instead.
func (*QuotaMetric) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{1}
}

func (x *QuotaMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Deprecated: Marked as deprecated in yandex/cloud/priv/quota/quota.proto.
func (x *QuotaMetric) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *QuotaMetric) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QuotaMetric) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

type MetricLimit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Limit int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *MetricLimit) Reset() {
	*x = MetricLimit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricLimit) ProtoMessage() {}

func (x *MetricLimit) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricLimit.ProtoReflect.Descriptor instead.
func (*MetricLimit) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{2}
}

func (x *MetricLimit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricLimit) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetQuotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CloudId string `protobuf:"bytes,1,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
}

func (x *GetQuotaRequest) Reset() {
	*x = GetQuotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaRequest) ProtoMessage() {}

func (x *GetQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaRequest.ProtoReflect.Descriptor instead.
func (*GetQuotaRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuotaRequest) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

type UpdateQuotaMetricRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CloudId string       `protobuf:"bytes,1,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	Metric  *MetricLimit `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
}

func (x *UpdateQuotaMetricRequest) Reset() {
	*x = UpdateQuotaMetricRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQuotaMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuotaMetricRequest) ProtoMessage() {}

func (x *UpdateQuotaMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuotaMetricRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuotaMetricRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateQuotaMetricRequest) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

func (x *UpdateQuotaMetricRequest) GetMetric() *MetricLimit {
	if x != nil {
		return x.Metric
	}
	return nil
}

type BatchUpdateQuotaMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CloudId string         `protobuf:"bytes,1,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	Metrics []*MetricLimit `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *BatchUpdateQuotaMetricsRequest) Reset() {
	*x = BatchUpdateQuotaMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchUpdateQuotaMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateQuotaMetricsRequest) ProtoMessage() {}

func (x *BatchUpdateQuotaMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateQuotaMetricsRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateQuotaMetricsRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{5}
}

func (x *BatchUpdateQuotaMetricsRequest) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

func (x *BatchUpdateQuotaMetricsRequest) GetMetrics() []*MetricLimit {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MoveQuotaMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceCloudId      string         `protobuf:"bytes,1,opt,name=source_cloud_id,json=sourceCloudId,proto3" json:"source_cloud_id,omitempty"`
	DestinationCloudId string         `protobuf:"bytes,2,opt,name=destination_cloud_id,json=destinationCloudId,proto3" json:"destination_cloud_id,omitempty"`
	MetricsDiff        []*MetricLimit `protobuf:"bytes,3,rep,name=metrics_diff,json=metricsDiff,proto3" json:"metrics_diff,omitempty"`
}

func (x *MoveQuotaMetricsRequest) Reset() {
	*x = MoveQuotaMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveQuotaMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveQuotaMetricsRequest) ProtoMessage() {}

func (x *MoveQuotaMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveQuotaMetricsRequest.ProtoReflect.Descriptor instead.
func (*MoveQuotaMetricsRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{6}
}

func (x *MoveQuotaMetricsRequest) GetSourceCloudId() string {
	if x != nil {
		return x.SourceCloudId
	}
	return ""
}

func (x *MoveQuotaMetricsRequest) GetDestinationCloudId() string {
	if x != nil {
		return x.DestinationCloudId
	}
	return ""
}

func (x *MoveQuotaMetricsRequest) GetMetricsDiff() []*MetricLimit {
	if x != nil {
		return x.MetricsDiff
	}
	return nil
}

type MoveQuotaMetricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceCloudUpdatedMetrics      []*MetricLimit `protobuf:"bytes,1,rep,name=source_cloud_updated_metrics,json=sourceCloudUpdatedMetrics,proto3" json:"source_cloud_updated_metrics,omitempty"`
	DestinationCloudUpdatedMetrics []*MetricLimit `protobuf:"bytes,2,rep,name=destination_cloud_updated_metrics,json=destinationCloudUpdatedMetrics,proto3" json:"destination_cloud_updated_metrics,omitempty"`
}

func (x *MoveQuotaMetricsResponse) Reset() {
	*x = MoveQuotaMetricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveQuotaMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveQuotaMetricsResponse) ProtoMessage() {}

func (x *MoveQuotaMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveQuotaMetricsResponse.ProtoReflect.Descriptor instead.
func (*MoveQuotaMetricsResponse) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{7}
}

func (x *MoveQuotaMetricsResponse) GetSourceCloudUpdatedMetrics() []*MetricLimit {
	if x != nil {
		return x.SourceCloudUpdatedMetrics
	}
	return nil
}

func (x *MoveQuotaMetricsResponse) GetDestinationCloudUpdatedMetrics() []*MetricLimit {
	if x != nil {
		return x.DestinationCloudUpdatedMetrics
	}
	return nil
}

type DoubleUpdateQuotaMetricRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceCloudId             string         `protobuf:"bytes,1,opt,name=source_cloud_id,json=sourceCloudId,proto3" json:"source_cloud_id,omitempty"`
	KnownSourceMetrics        []*MetricLimit `protobuf:"bytes,2,rep,name=known_source_metrics,json=knownSourceMetrics,proto3" json:"known_source_metrics,omitempty"`
	UpdatedSourceMetrics      []*MetricLimit `protobuf:"bytes,3,rep,name=updated_source_metrics,json=updatedSourceMetrics,proto3" json:"updated_source_metrics,omitempty"`
	DestinationCloudId        string         `protobuf:"bytes,4,opt,name=destination_cloud_id,json=destinationCloudId,proto3" json:"destination_cloud_id,omitempty"`
	KnownDestinationMetrics   []*MetricLimit `protobuf:"bytes,5,rep,name=known_destination_metrics,json=knownDestinationMetrics,proto3" json:"known_destination_metrics,omitempty"`
	UpdatedDestinationMetrics []*MetricLimit `protobuf:"bytes,6,rep,name=updated_destination_metrics,json=updatedDestinationMetrics,proto3" json:"updated_destination_metrics,omitempty"`
}

func (x *DoubleUpdateQuotaMetricRequest) Reset() {
	*x = DoubleUpdateQuotaMetricRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleUpdateQuotaMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleUpdateQuotaMetricRequest) ProtoMessage() {}

func (x *DoubleUpdateQuotaMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleUpdateQuotaMetricRequest.ProtoReflect.Descriptor instead.
func (*DoubleUpdateQuotaMetricRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{8}
}

func (x *DoubleUpdateQuotaMetricRequest) GetSourceCloudId() string {
	if x != nil {
		return x.SourceCloudId
	}
	return ""
}

func (x *DoubleUpdateQuotaMetricRequest) GetKnownSourceMetrics() []*MetricLimit {
	if x != nil {
		return x.KnownSourceMetrics
	}
	return nil
}

func (x *DoubleUpdateQuotaMetricRequest) GetUpdatedSourceMetrics() []*MetricLimit {
	if x != nil {
		return x.UpdatedSourceMetrics
	}
	return nil
}

func (x *DoubleUpdateQuotaMetricRequest) GetDestinationCloudId() string {
	if x != nil {
		return x.DestinationCloudId
	}
	return ""
}

func (x *DoubleUpdateQuotaMetricRequest) GetKnownDestinationMetrics() []*MetricLimit {
	if x != nil {
		return x.KnownDestinationMetrics
	}
	return nil
}

func (x *DoubleUpdateQuotaMetricRequest) GetUpdatedDestinationMetrics() []*MetricLimit {
	if x != nil {
		return x.UpdatedDestinationMetrics
	}
	return nil
}

type GetQuotaDefaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQuotaDefaultRequest) Reset() {
	*x = GetQuotaDefaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotaDefaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaDefaultRequest) ProtoMessage() {}

func (x *GetQuotaDefaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaDefaultRequest.ProtoReflect.Descriptor instead.
func (*GetQuotaDefaultRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{9}
}

type GetQuotaDefaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics []*MetricLimit `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *GetQuotaDefaultResponse) Reset() {
	*x = GetQuotaDefaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotaDefaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaDefaultResponse) ProtoMessage() {}

func (x *GetQuotaDefaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaDefaultResponse.ProtoReflect.Descriptor instead.
func (*GetQuotaDefaultResponse) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{10}
}

func (x *GetQuotaDefaultResponse) GetMetrics() []*MetricLimit {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type QuotaFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CloudId    string                    `protobuf:"bytes,1,opt,name=cloud_id,json=cloudId,proto3" json:"cloud_id,omitempty"`
	Violations []*QuotaFailure_Violation `protobuf:"bytes,2,rep,name=violations,proto3" json:"violations,omitempty"`
}

func (x *QuotaFailure) Reset() {
	*x = QuotaFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuotaFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaFailure) ProtoMessage() {}

func (x *QuotaFailure) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaFailure.ProtoReflect.Descriptor instead.
func (*QuotaFailure) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{11}
}

func (x *QuotaFailure) GetCloudId() string {
	if x != nil {
		return x.CloudId
	}
	return ""
}

func (x *QuotaFailure) GetViolations() []*QuotaFailure_Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

type QuotaFailure_Violation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metric   *QuotaMetric `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Required int64        `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"` // new value for the MetricLimit.limit, so it is: old limit + delta
}

func (x *QuotaFailure_Violation) Reset() {
	*x = QuotaFailure_Violation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuotaFailure_Violation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaFailure_Violation) ProtoMessage() {}

func (x *QuotaFailure_Violation) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_quota_quota_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaFailure_Violation.ProtoReflect.Descriptor instead.
func (*QuotaFailure_Violation) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP(), []int{11, 0}
}

func (x *QuotaFailure_Violation) GetMetric() *QuotaMetric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *QuotaFailure_Violation) GetRequired() int64 {
	if x != nil {
		return x.Required
	}
	return 0
}

var File_yandex_cloud_priv_quota_quota_proto protoreflect.FileDescriptor

var file_yandex_cloud_priv_quota_quota_proto_rawDesc = []byte{
	0x0a, 0x23, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70,
	0x72, 0x69, 0x76, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x1a, 0x22,
	0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x72, 0x69,
	0x76, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x62, 0x0a, 0x05, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x71, 0x75, 0x6f, 0x74,
	0x61, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x07, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x67, 0x0a, 0x0b, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x42, 0x02, 0x18, 0x01, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x37, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x3a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xa8,
	0x89, 0x31, 0x01, 0xca, 0x89, 0x31, 0x04, 0x3c, 0x3d, 0x35, 0x30, 0x52, 0x07, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x27, 0x0a, 0x08, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x0c, 0xa8, 0x89, 0x31, 0x01, 0xca, 0x89, 0x31, 0x04, 0x3c, 0x3d, 0x35,
	0x30, 0x52, 0x07, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x79, 0x61, 0x6e,
	0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x71,
	0x75, 0x6f, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x22, 0x89, 0x01, 0x0a, 0x1e, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xa8,
	0x89, 0x31, 0x01, 0xca, 0x89, 0x31, 0x04, 0x3c, 0x3d, 0x35, 0x30, 0x52, 0x07, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x07, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x22, 0xd8, 0x01, 0x0a, 0x17, 0x4d, 0x6f, 0x76, 0x65, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x34, 0x0a, 0x0f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xa8, 0x89, 0x31, 0x01, 0xca,
	0x89, 0x31, 0x04, 0x3c, 0x3d, 0x35, 0x30, 0x52, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43,
	0x6c, 0x6f, 0x75, 0x64, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x14, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xa8, 0x89, 0x31, 0x01, 0xca, 0x89, 0x31, 0x04, 0x3c, 0x3d,
	0x35, 0x30, 0x52, 0x12, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6c, 0x6f, 0x75, 0x64, 0x49, 0x64, 0x12, 0x47, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x5f, 0x64, 0x69, 0x66, 0x66, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x79,
	0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x52, 0x0b, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x44, 0x69, 0x66, 0x66, 0x22,
	0xf2, 0x01, 0x0a, 0x18, 0x4d, 0x6f, 0x76, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x1c,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x19, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x43, 0x6c, 0x6f, 0x75, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x12, 0x6f, 0x0a, 0x21, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x52, 0x1e, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x22, 0x92, 0x04, 0x0a, 0x1e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x0c, 0xa8, 0x89, 0x31, 0x01, 0xca, 0x89, 0x31, 0x04, 0x3c, 0x3d, 0x35, 0x30, 0x52, 0x0d,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x49, 0x64, 0x12, 0x56, 0x0a,
	0x14, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x79, 0x61,
	0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e,
	0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x52, 0x12, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x5a, 0x0a, 0x16, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x14, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x12, 0x3e, 0x0a, 0x14, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x0c, 0xa8, 0x89, 0x31, 0x01, 0xca, 0x89, 0x31, 0x04, 0x3c, 0x3d, 0x35, 0x30, 0x52, 0x12, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x49,
	0x64, 0x12, 0x60, 0x0a, 0x19, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x17, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x12, 0x64, 0x0a, 0x1b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65,
	0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x71, 0x75, 0x6f,
	0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x19,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x51, 0x75, 0x6f, 0x74, 0x61, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0xe1,
	0x01, 0x0a, 0x0c, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x49, 0x64, 0x12, 0x4f, 0x0a, 0x0a, 0x76, 0x69,
	0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f,
	0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x46, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x2e, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0a, 0x76, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x65, 0x0a, 0x09, 0x56,
	0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65,
	0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x71, 0x75, 0x6f,
	0x74, 0x61, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x42, 0x50, 0x42, 0x02, 0x50, 0x51, 0x5a, 0x4a, 0x61, 0x2e, 0x79, 0x61, 0x6e, 0x64,
	0x65, 0x78, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x72, 0x75, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2f, 0x62, 0x69, 0x74, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x3b, 0x71,
	0x75, 0x6f, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yandex_cloud_priv_quota_quota_proto_rawDescOnce sync.Once
	file_yandex_cloud_priv_quota_quota_proto_rawDescData = file_yandex_cloud_priv_quota_quota_proto_rawDesc
)

func file_yandex_cloud_priv_quota_quota_proto_rawDescGZIP() []byte {
	file_yandex_cloud_priv_quota_quota_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_priv_quota_quota_proto_rawDescData = protoimpl.X.CompressGZIP(file_yandex_cloud_priv_quota_quota_proto_rawDescData)
	})
	return file_yandex_cloud_priv_quota_quota_proto_rawDescData
}

var file_yandex_cloud_priv_quota_quota_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_yandex_cloud_priv_quota_quota_proto_goTypes = []interface{}{
	(*Quota)(nil),                          // 0: yandex.cloud.priv.quota.Quota
	(*QuotaMetric)(nil),                    // 1: yandex.cloud.priv.quota.QuotaMetric
	(*MetricLimit)(nil),                    // 2: yandex.cloud.priv.quota.MetricLimit
	(*GetQuotaRequest)(nil),                // 3: yandex.cloud.priv.quota.GetQuotaRequest
	(*UpdateQuotaMetricRequest)(nil),       // 4: yandex.cloud.priv.quota.UpdateQuotaMetricRequest
	(*BatchUpdateQuotaMetricsRequest)(nil), // 5: yandex.cloud.priv.quota.BatchUpdateQuotaMetricsRequest
	(*MoveQuotaMetricsRequest)(nil),        // 6: yandex.cloud.priv.quota.MoveQuotaMetricsRequest
	(*MoveQuotaMetricsResponse)(nil),       // 7: yandex.cloud.priv.quota.MoveQuotaMetricsResponse
	(*DoubleUpdateQuotaMetricRequest)(nil), // 8: yandex.cloud.priv.quota.DoubleUpdateQuotaMetricRequest
	(*GetQuotaDefaultRequest)(nil),         // 9: yandex.cloud.priv.quota.GetQuotaDefaultRequest
	(*GetQuotaDefaultResponse)(nil),        // 10: yandex.cloud.priv.quota.GetQuotaDefaultResponse
	(*QuotaFailure)(nil),                   // 11: yandex.cloud.priv.quota.QuotaFailure
	(*QuotaFailure_Violation)(nil),         // 12: yandex.cloud.priv.quota.QuotaFailure.Violation
}
var file_yandex_cloud_priv_quota_quota_proto_depIdxs = []int32{
	1,  // 0: yandex.cloud.priv.quota.Quota.metrics:type_name -> yandex.cloud.priv.quota.QuotaMetric
	2,  // 1: yandex.cloud.priv.quota.UpdateQuotaMetricRequest.metric:type_name -> yandex.cloud.priv.quota.MetricLimit
	2,  // 2: yandex.cloud.priv.quota.BatchUpdateQuotaMetricsRequest.metrics:type_name -> yandex.cloud.priv.quota.MetricLimit
	2,  // 3: yandex.cloud.priv.quota.MoveQuotaMetricsRequest.metrics_diff:type_name -> yandex.cloud.priv.quota.MetricLimit
	2,  // 4: yandex.cloud.priv.quota.MoveQuotaMetricsResponse.source_cloud_updated_metrics:type_name -> yandex.cloud.priv.quota.MetricLimit
	2,  // 5: yandex.cloud.priv.quota.MoveQuotaMetricsResponse.destination_cloud_updated_metrics:type_name -> yandex.cloud.priv.quota.MetricLimit
	2,  // 6: yandex.cloud.priv.quota.DoubleUpdateQuotaMetricRequest.known_source_metrics:type_name -> yandex.cloud.priv.quota.MetricLimit
	2,  // 7: yandex.cloud.priv.quota.DoubleUpdateQuotaMetricRequest.updated_source_metrics:type_name -> yandex.cloud.priv.quota.MetricLimit
	2,  // 8: yandex.cloud.priv.quota.DoubleUpdateQuotaMetricRequest.known_destination_metrics:type_name -> yandex.cloud.priv.quota.MetricLimit
	2,  // 9: yandex.cloud.priv.quota.DoubleUpdateQuotaMetricRequest.updated_destination_metrics:type_name -> yandex.cloud.priv.quota.MetricLimit
	2,  // 10: yandex.cloud.priv.quota.GetQuotaDefaultResponse.metrics:type_name -> yandex.cloud.priv.quota.MetricLimit
	12, // 11: yandex.cloud.priv.quota.QuotaFailure.violations:type_name -> yandex.cloud.priv.quota.QuotaFailure.Violation
	1,  // 12: yandex.cloud.priv.quota.QuotaFailure.Violation.metric:type_name -> yandex.cloud.priv.quota.QuotaMetric
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_yandex_cloud_priv_quota_quota_proto_init() }
func file_yandex_cloud_priv_quota_quota_proto_init() {
	if File_yandex_cloud_priv_quota_quota_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quota); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuotaMetric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricLimit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQuotaMetricRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchUpdateQuotaMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveQuotaMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveQuotaMetricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleUpdateQuotaMetricRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotaDefaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotaDefaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuotaFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_quota_quota_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuotaFailure_Violation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yandex_cloud_priv_quota_quota_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yandex_cloud_priv_quota_quota_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_priv_quota_quota_proto_depIdxs,
		MessageInfos:      file_yandex_cloud_priv_quota_quota_proto_msgTypes,
	}.Build()
	File_yandex_cloud_priv_quota_quota_proto = out.File
	file_yandex_cloud_priv_quota_quota_proto_rawDesc = nil
	file_yandex_cloud_priv_quota_quota_proto_goTypes = nil
	file_yandex_cloud_priv_quota_quota_proto_depIdxs = nil
}
