FROM registry.yandex.net/data-transfer/tests/postgres-postgis-wal2json:13-3.3-2.5@sha256:5ab2b7b9f2392f0fa0e70726f94e0b44ce5cc370bfac56ac4b590f163a38e110
COPY 20-init.sql /docker-entrypoint-initdb.d/20-init.sql
