// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.3
// source: yandex/cloud/priv/oauth/v1/login_history_service.proto

package oauth

import (
	_ "github.com/doublecloud/tross/cloud/bitbucket/private-api/yandex/cloud/priv"
	oauth "github.com/doublecloud/tross/cloud/bitbucket/private-api/yandex/cloud/priv/oauth"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListLoginsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The "Cookie" HTTP-header passed from the end-user's client
	CookieHeader string `protobuf:"bytes,1,opt,name=cookie_header,json=cookieHeader,proto3" json:"cookie_header,omitempty"`
	PageSize     int64  `protobuf:"varint,100,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken    string `protobuf:"bytes,101,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
}

func (x *ListLoginsRequest) Reset() {
	*x = ListLoginsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLoginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoginsRequest) ProtoMessage() {}

func (x *ListLoginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoginsRequest.ProtoReflect.Descriptor instead.
func (*ListLoginsRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListLoginsRequest) GetCookieHeader() string {
	if x != nil {
		return x.CookieHeader
	}
	return ""
}

func (x *ListLoginsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLoginsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type DeviceLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// claims of the logged-in subject
	SubjectClaims *oauth.SubjectClaims `protobuf:"bytes,1,opt,name=subject_claims,json=subjectClaims,proto3" json:"subject_claims,omitempty"`
	// when last time SessionService/Create was successfully completed for the subject
	LastSessionCreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_session_created_at,json=lastSessionCreatedAt,proto3" json:"last_session_created_at,omitempty"`
}

func (x *DeviceLogin) Reset() {
	*x = DeviceLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceLogin) ProtoMessage() {}

func (x *DeviceLogin) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceLogin.ProtoReflect.Descriptor instead.
func (*DeviceLogin) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceLogin) GetSubjectClaims() *oauth.SubjectClaims {
	if x != nil {
		return x.SubjectClaims
	}
	return nil
}

func (x *DeviceLogin) GetLastSessionCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSessionCreatedAt
	}
	return nil
}

type ListLoginsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Fields `sub` & `federation` of nested subject claims are guaranteed to be filled.
	// They should be used for building redirects to federation login URLs and login entry deletion requests.
	Logins        []*DeviceLogin `protobuf:"bytes,1,rep,name=logins,proto3" json:"logins,omitempty"`
	NextPageToken string         `protobuf:"bytes,100,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (x *ListLoginsResponse) Reset() {
	*x = ListLoginsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLoginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoginsResponse) ProtoMessage() {}

func (x *ListLoginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoginsResponse.ProtoReflect.Descriptor instead.
func (*ListLoginsResponse) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListLoginsResponse) GetLogins() []*DeviceLogin {
	if x != nil {
		return x.Logins
	}
	return nil
}

func (x *ListLoginsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteDeviceLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The "Cookie" HTTP header containing the "yc_device" cookie.
	CookieHeader string `protobuf:"bytes,1,opt,name=cookie_header,json=cookieHeader,proto3" json:"cookie_header,omitempty"`
	// Subject identifier (SubjectClaims.sub) of the login history entry to remove.
	SubjectId string `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
}

func (x *DeleteDeviceLoginRequest) Reset() {
	*x = DeleteDeviceLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDeviceLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceLoginRequest) ProtoMessage() {}

func (x *DeleteDeviceLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceLoginRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeviceLoginRequest) Descriptor() ([]byte, []int) {
	return file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteDeviceLoginRequest) GetCookieHeader() string {
	if x != nil {
		return x.CookieHeader
	}
	return ""
}

func (x *DeleteDeviceLoginRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

var File_yandex_cloud_priv_oauth_v1_login_history_service_proto protoreflect.FileDescriptor

var file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDesc = []byte{
	0x0a, 0x36, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70,
	0x72, 0x69, 0x76, 0x2f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x6f, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x22, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x2f, 0x70, 0x72, 0x69, 0x76, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x2f, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74,
	0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x24, 0x79, 0x61, 0x6e, 0x64, 0x65,
	0x78, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x2f, 0x6f, 0x61, 0x75,
	0x74, 0x68, 0x2f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa4, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x5f,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x17, 0xa8, 0x89,
	0x31, 0x01, 0xca, 0x89, 0x31, 0x07, 0x3c, 0x3d, 0x33, 0x32, 0x37, 0x36, 0x38, 0xc8, 0x8f, 0x31,
	0x01, 0xd0, 0x8f, 0x31, 0x08, 0x52, 0x0c, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x64, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0a, 0xba, 0x89, 0x31, 0x06, 0x30, 0x2d, 0x31, 0x30,
	0x30, 0x30, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x28, 0x0a, 0x0a,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x09, 0xca, 0x89, 0x31, 0x05, 0x3c, 0x3d, 0x31, 0x30, 0x30, 0x52, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xaf, 0x01, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x4d, 0x0a, 0x0e, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x2e, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x73, 0x12, 0x51, 0x0a, 0x17, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x14, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x7d, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f,
	0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x2e, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x12,
	0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61,
	0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x85, 0x01, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x5f, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x17, 0xa8, 0x89, 0x31,
	0x01, 0xca, 0x89, 0x31, 0x07, 0x3c, 0x3d, 0x33, 0x32, 0x37, 0x36, 0x38, 0xc8, 0x8f, 0x31, 0x01,
	0xd0, 0x8f, 0x31, 0x08, 0x52, 0x0c, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x2b, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0c, 0xa8, 0x89, 0x31, 0x01, 0xca, 0x89, 0x31, 0x04,
	0x3c, 0x3d, 0x35, 0x30, 0x52, 0x09, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x32,
	0xd4, 0x01, 0x0a, 0x13, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x2d, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x2e, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e,
	0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x2e, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x34, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65,
	0x78, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x6f, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x5d, 0x42, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5a, 0x4d, 0x61, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78,
	0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x72, 0x75, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x62,
	0x69, 0x74, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x2f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x3b,
	0x6f, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDescOnce sync.Once
	file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDescData = file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDesc
)

func file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDescGZIP() []byte {
	file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDescOnce.Do(func() {
		file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDescData)
	})
	return file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDescData
}

var file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_yandex_cloud_priv_oauth_v1_login_history_service_proto_goTypes = []interface{}{
	(*ListLoginsRequest)(nil),        // 0: yandex.cloud.priv.oauth.v1.ListLoginsRequest
	(*DeviceLogin)(nil),              // 1: yandex.cloud.priv.oauth.v1.DeviceLogin
	(*ListLoginsResponse)(nil),       // 2: yandex.cloud.priv.oauth.v1.ListLoginsResponse
	(*DeleteDeviceLoginRequest)(nil), // 3: yandex.cloud.priv.oauth.v1.DeleteDeviceLoginRequest
	(*oauth.SubjectClaims)(nil),      // 4: yandex.cloud.priv.oauth.SubjectClaims
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 6: google.protobuf.Empty
}
var file_yandex_cloud_priv_oauth_v1_login_history_service_proto_depIdxs = []int32{
	4, // 0: yandex.cloud.priv.oauth.v1.DeviceLogin.subject_claims:type_name -> yandex.cloud.priv.oauth.SubjectClaims
	5, // 1: yandex.cloud.priv.oauth.v1.DeviceLogin.last_session_created_at:type_name -> google.protobuf.Timestamp
	1, // 2: yandex.cloud.priv.oauth.v1.ListLoginsResponse.logins:type_name -> yandex.cloud.priv.oauth.v1.DeviceLogin
	0, // 3: yandex.cloud.priv.oauth.v1.LoginHistoryService.List:input_type -> yandex.cloud.priv.oauth.v1.ListLoginsRequest
	3, // 4: yandex.cloud.priv.oauth.v1.LoginHistoryService.Delete:input_type -> yandex.cloud.priv.oauth.v1.DeleteDeviceLoginRequest
	2, // 5: yandex.cloud.priv.oauth.v1.LoginHistoryService.List:output_type -> yandex.cloud.priv.oauth.v1.ListLoginsResponse
	6, // 6: yandex.cloud.priv.oauth.v1.LoginHistoryService.Delete:output_type -> google.protobuf.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_yandex_cloud_priv_oauth_v1_login_history_service_proto_init() }
func file_yandex_cloud_priv_oauth_v1_login_history_service_proto_init() {
	if File_yandex_cloud_priv_oauth_v1_login_history_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLoginsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLoginsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDeviceLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yandex_cloud_priv_oauth_v1_login_history_service_proto_goTypes,
		DependencyIndexes: file_yandex_cloud_priv_oauth_v1_login_history_service_proto_depIdxs,
		MessageInfos:      file_yandex_cloud_priv_oauth_v1_login_history_service_proto_msgTypes,
	}.Build()
	File_yandex_cloud_priv_oauth_v1_login_history_service_proto = out.File
	file_yandex_cloud_priv_oauth_v1_login_history_service_proto_rawDesc = nil
	file_yandex_cloud_priv_oauth_v1_login_history_service_proto_goTypes = nil
	file_yandex_cloud_priv_oauth_v1_login_history_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LoginHistoryServiceClient is the client API for LoginHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginHistoryServiceClient interface {
	// Returns the device's login history by client's cookies.
	//
	// gRPC error codes
	// InvalidArgument: the Cookie header field is malformed.
	List(ctx context.Context, in *ListLoginsRequest, opts ...grpc.CallOption) (*ListLoginsResponse, error)
	// Removes the specified record from the device's login history.
	//
	// gRPC error codes
	// InvalidArgument: the Cookie header field is malformed.
	Delete(ctx context.Context, in *DeleteDeviceLoginRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type loginHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginHistoryServiceClient(cc grpc.ClientConnInterface) LoginHistoryServiceClient {
	return &loginHistoryServiceClient{cc}
}

func (c *loginHistoryServiceClient) List(ctx context.Context, in *ListLoginsRequest, opts ...grpc.CallOption) (*ListLoginsResponse, error) {
	out := new(ListLoginsResponse)
	err := c.cc.Invoke(ctx, "/yandex.cloud.priv.oauth.v1.LoginHistoryService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginHistoryServiceClient) Delete(ctx context.Context, in *DeleteDeviceLoginRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/yandex.cloud.priv.oauth.v1.LoginHistoryService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginHistoryServiceServer is the server API for LoginHistoryService service.
type LoginHistoryServiceServer interface {
	// Returns the device's login history by client's cookies.
	//
	// gRPC error codes
	// InvalidArgument: the Cookie header field is malformed.
	List(context.Context, *ListLoginsRequest) (*ListLoginsResponse, error)
	// Removes the specified record from the device's login history.
	//
	// gRPC error codes
	// InvalidArgument: the Cookie header field is malformed.
	Delete(context.Context, *DeleteDeviceLoginRequest) (*emptypb.Empty, error)
}

// UnimplementedLoginHistoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLoginHistoryServiceServer struct {
}

func (*UnimplementedLoginHistoryServiceServer) List(context.Context, *ListLoginsRequest) (*ListLoginsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedLoginHistoryServiceServer) Delete(context.Context, *DeleteDeviceLoginRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterLoginHistoryServiceServer(s *grpc.Server, srv LoginHistoryServiceServer) {
	s.RegisterService(&_LoginHistoryService_serviceDesc, srv)
}

func _LoginHistoryService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginHistoryServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yandex.cloud.priv.oauth.v1.LoginHistoryService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginHistoryServiceServer).List(ctx, req.(*ListLoginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginHistoryService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginHistoryServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yandex.cloud.priv.oauth.v1.LoginHistoryService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginHistoryServiceServer).Delete(ctx, req.(*DeleteDeviceLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoginHistoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "yandex.cloud.priv.oauth.v1.LoginHistoryService",
	HandlerType: (*LoginHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _LoginHistoryService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _LoginHistoryService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yandex/cloud/priv/oauth/v1/login_history_service.proto",
}
