image: ghcr.io/doublecloud/transfer:v0.0.0-rc8

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "2048Mi"
    cpu: "2000m"

transferSpec:
  id: dtttesthelm
  type: SNAPSHOT_ONLY  # Options: SNAPSHOT_ONLY, INCREMENT_ONLY, SNAPSHOT_AND_INCREMENT
  regular_snapshot:
    enabled: false
    cron_expression: "0 1 * * *"
  src:
    type: pg
    params:
      {
      }
  dst:
    type: stdout
    params:
      {
      }

coordinator:
  job_count: 1  # Number of parallel job instances
  process_count: 4 # Number of in-worker threads to spawn
  type: memory
  bucket: NO_BUCKET

env:
  NO_KEY: NO_VALUE

log:
  level: info # ("panic", "fatal", "error", "warning", "info", "debug")
  config: minimal # ("console", "json", "minimal")
