CREATE TABLE test_table_with_serial
(
    id serial
);

CREATE SEQUENCE test_seq;
CREATE TABLE test_table_with_default1
(
    id int DEFAULT NEXTVAL('test_seq'::regclass)
);
CREATE TABLE test_table_with_default2
(
    id int DEFAULT NEXTVAL('test_seq'::regclass)
);

CREATE SEQUENCE test_seq_without_dependents;

CREATE TABLE table_with_gbdai_seq(i INT NOT NULL, t TEXT);
ALTER TABLE table_with_gbdai_seq 
    ALTER COLUMN i ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME gbdai_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

INSERT INTO table_with_gbdai_seq(t) VALUES ('a'), ('b'), ('c');
