# permissions for end users to view transfers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: transfer-viewer-role
rules:
- apiGroups:
  - trsfrcrd.dc
  resources:
  - transfers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trsfrcrd.dc
  resources:
  - transfers/status
  verbs:
  - get
