{
 "title": "Example Grafana Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "resource_id", "label": "resource_id", "query": { "query": "label_values(resource_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Source reader active",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (resource_id) (publisher_consumer_active{resource_id=\"$resource_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of fatal errors during source read",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum by (resource_id) (rate(publisher_consumer_fatal{resource_id=\"$resource_id\"}[2m]))",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Amount of changeitems derived from source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by (resource_id) (rate(sinker_pusher_data_changeitems{resource_id=\"$resource_id\"}[2m]))",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Amount of changeitems pushed to target",
   "type": "timeseries",
   "description": "Amount of changeitems which where successfully pushed to target",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (resource_id) (rate(sinker_pusher_data_changeitems{resource_id=\"$resource_id\"}[2m]))",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Amount of changeitems pushed to target (by tables)",
   "type": "timeseries",
   "description": "Amount of changeitems which where successfully pushed to target",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum by (resource_id, target_id, source_type, source_type, source_id, table) (rate(sinker_table_rows{resource_id=\"$resource_id\"}[2m]))",
     "legendFormat": "{{table}} {{resource_id}}"
    }
   ]
  },
  {
   "title": "Max Data Lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (resource_id) (sinker_pusher_time_row_max_lag_sec{resource_id=\"$resource_id\"})",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Average time elapsed during push to target",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (resource_id) (rate(sinker_time_push{resource_id=\"$resource_id\"}[2m]))",
     "legendFormat": "{{resource_id}}"
    }
   ]
  }
 ]
}