//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoordinatorConfig) DeepCopyInto(out *CoordinatorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoordinatorConfig.
func (in *CoordinatorConfig) DeepCopy() *CoordinatorConfig {
	if in == nil {
		return nil
	}
	out := new(CoordinatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncrementalTable) DeepCopyInto(out *IncrementalTable) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncrementalTable.
func (in *IncrementalTable) DeepCopy() *IncrementalTable {
	if in == nil {
		return nil
	}
	out := new(IncrementalTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegularSnapshot) DeepCopyInto(out *RegularSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegularSnapshot.
func (in *RegularSnapshot) DeepCopy() *RegularSnapshot {
	if in == nil {
		return nil
	}
	out := new(RegularSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transfer) DeepCopyInto(out *Transfer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	out.Config = in.Config
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transfer.
func (in *Transfer) DeepCopy() *Transfer {
	if in == nil {
		return nil
	}
	out := new(Transfer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Transfer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferConfig) DeepCopyInto(out *TransferConfig) {
	*out = *in
	out.Coordinator = in.Coordinator
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferConfig.
func (in *TransferConfig) DeepCopy() *TransferConfig {
	if in == nil {
		return nil
	}
	out := new(TransferConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferList) DeepCopyInto(out *TransferList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Transfer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferList.
func (in *TransferList) DeepCopy() *TransferList {
	if in == nil {
		return nil
	}
	out := new(TransferList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransferList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferSpec) DeepCopyInto(out *TransferSpec) {
	*out = *in
	out.Src = in.Src
	out.Dst = in.Dst
	if in.Incremental != nil {
		in, out := &in.Incremental, &out.Incremental
		*out = make([]IncrementalTable, len(*in))
		copy(*out, *in)
	}
	if in.RegularSnapshot != nil {
		in, out := &in.RegularSnapshot, &out.RegularSnapshot
		*out = new(RegularSnapshot)
		**out = **in
	}
	if in.DataObjects != nil {
		in, out := &in.DataObjects, &out.DataObjects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferSpec.
func (in *TransferSpec) DeepCopy() *TransferSpec {
	if in == nil {
		return nil
	}
	out := new(TransferSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferStatus) DeepCopyInto(out *TransferStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferStatus.
func (in *TransferStatus) DeepCopy() *TransferStatus {
	if in == nil {
		return nil
	}
	out := new(TransferStatus)
	in.DeepCopyInto(out)
	return out
}
