env:
  AWS_REGION: eu-central-1

coordinator:
  type: s3
  bucket: place_your_bucket
transferSpec:
  regular_snapshot:
    incremental:
      - namespace: public
        name: playing_with_neon
        cursor_field: id
    enabled: true
  src:
    type: pg
    params:
      Hosts:
        - YOUR_NEON_DB
      Database: YOUR_DB_NAME
      User: YOUR_DB_USER
      Password: YOUR_DB_PASSWORD
      Port: 5432
      BatchSize: 1024
      SlotByteLagLimit: 53687091200
      EnableTLS: true
      KeeperSchema: public
      DesiredTableSize: 1073741824
      SnapshotDegreeOfParallelism: 4
  dst:
    type: ch
    params:
      User: YOUR_DC_USER
      Password: YOUR_DC_PASSWORD
      ShardsList:
        - Hosts:
            - YOUR_DC_HOST
      Database: default
      HTTPPort: 8443
      SSLEnabled: true
      NativePort: 9440
      MigrationOptions:
        AddNewColumns: true
      InsertParams:
        MaterializedViewsIgnoreErrors: true
      RetryCount: 20
      UseSchemaInTableName: true
      Interval: 1000000000
      Cleanup: Drop
      BufferTriggingSize: 536870912
