apiVersion: batch/v1
kind: Job
metadata:
  name: transfer-{{ .Values.transferSpec.id }}-snapshot
spec:
  completions: {{ .Values.snapshot.worker_count }}
  parallelism: {{ .Values.snapshot.worker_count }}
  completionMode: Indexed
  backoffLimit: 6
  template:
    spec:
    {{- include "transfer.spec" (dict "commandType" "activate" "Values" .Values) | nindent 6 }}
