apiVersion: v1
kind: ConfigMap
metadata:
  name: { { .Release.Name } }
  labels: { { - include "common.labels" . | nindent 4 } }
data:
  config.yaml: |
    id: {{ .Values.transferSpec.id | default .Release.Name | replace "-" "_" }}
    type: {{ .Values.transferSpec.type }}
    src:
      type: {{ .Values.transferSpec.src.type }}
      params: |
        {{ .Values.transferSpec.src.params | toJson }}
    dst:
      type: {{ .Values.transferSpec.dst.type }}
      params: |
        {{ .Values.transferSpec.dst.params | toJson }}
    {{if .Values.transferSpec.regular_snapshot}}
    regular_snapshot: {{ .Values.transferSpec.regular_snapshot | toJson }}
    {{end}}
    {{if .Values.transferSpec.data_objects}}
    data_objects: {{ .Values.transferSpec.data_objects | toJson }}
    {{end}}
    {{if .Values.transferSpec.transformation}}
    transformation: {{ .Values.transferSpec.transformation | toJson }}
    {{end}}
