{{- if (.Values.serviceAccount).create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- .Values.serviceAccount.annotations | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
