name: Auto build and publish of Transfer image

on:
  pull_request:
    branches:
      - 'release-*'

jobs:
  trigger-build:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ github.event.pull_request.head.ref }}

