name: Auto build and publish of Transfer image

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  trigger-build:
    uses: ./.github/release.yml
    with:
      ref: ${{ github.ref }}  # The branch name
      version: ${{ github.ref_name }}

