name: Auto build and publish of Transfer image

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  trigger-manual-build:
    runs-on: ubuntu-latest
    steps:
      - name: Publish docker image
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Manual build and publish of Transfer image
          ref: ${{ github.ref }}  # The branch name
          version: '{"version": "${{ github.ref_name }}"}'

