name: Auto build and publish of Transfer image

on:
  push:
    branches:
      - 'main'

  pull_request:
    paths:
      - '.github/**'

jobs:
  trigger-build-dev:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/release.yml
    with:
      version: dev

  trigger-build-latest:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/release.yml
    with:
      version: latest

