name: Auto build and publish of Transfer image

on:
  push:
    branches:
      - 'main'

jobs:
  trigger-build-dev:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/release.yml
    with:
      version: dev
      extra_args: '--snapshot'

  trigger-build-latest:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/release.yml
    with:
      version: latest
      extra_args: '--snapshot'

